services:
  postgres:
    container_name: main_db
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=gameserver'
      - 'POSTGRES_PASSWORD=gameserver_87468757'
      - 'POSTGRES_USER=admin'
    ports:
      - "5432:5432"
